"""update payment_event schema

Revision ID: af79fc0a73cb
Revises: 137a40463c00
Create Date: 2026-07-16 15:16:53.782779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af79fc0a73cb'
down_revision: Union[str, Sequence[str], None] = '137a40463c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_events', sa.Column('transaction_pk', sa.Integer(), nullable=False))
    op.add_column('payment_events', sa.Column('external_transaction_id', sa.String(), nullable=False))
    op.add_column('payment_events', sa.Column('external_merchant_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_payment_events_transaction_id'), table_name='payment_events')
    op.create_index(op.f('ix_payment_events_external_merchant_id'), 'payment_events', ['external_merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_events_external_transaction_id'), 'payment_events', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_events_transaction_pk'), 'payment_events', ['transaction_pk'], unique=False)
    op.drop_constraint(op.f('payment_events_transaction_id_fkey'), 'payment_events', type_='foreignkey')
    op.create_foreign_key(None, 'payment_events', 'transactions', ['transaction_pk'], ['id'])
    op.drop_column('payment_events', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_events', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_events', type_='foreignkey')
    op.create_foreign_key(op.f('payment_events_transaction_id_fkey'), 'payment_events', 'transactions', ['transaction_id'], ['id'])
    op.drop_index(op.f('ix_payment_events_transaction_pk'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_external_transaction_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_external_merchant_id'), table_name='payment_events')
    op.create_index(op.f('ix_payment_events_transaction_id'), 'payment_events', ['transaction_id'], unique=False)
    op.drop_column('payment_events', 'external_merchant_id')
    op.drop_column('payment_events', 'external_transaction_id')
    op.drop_column('payment_events', 'transaction_pk')
    # ### end Alembic commands ###
